# Generated by Django 5.2.14 on 2026-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_survey_completed",
            field=models.BooleanField(
                default=False, verbose_name="Encuesta Completada"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="monthly_income",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Ingresos Mensuales",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="personal_activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Estudiante"),
                    ("employee", "Empleado"),
                    ("freelancer", "Independiente"),
                    ("unemployed", "En búsqueda"),
                    ("retired", "Jubilado"),
                ],
                max_length=20,
                null=True,
                verbose_name="Actividad Personal",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tastes",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Intereses y Gustos",
            ),
        ),
    ]
