# Generated by Django 5.2.14 on 2026-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_survey_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Código de verificación",
            ),
        ),
    ]
