# Generated by Django 5.2.14 on 2026-07-01 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Servicio"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Costo"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("semiannually", "Semestral"),
                            ("annually", "Anual"),
                        ],
                        default="monthly",
                        max_length=15,
                        verbose_name="Frecuencia de Pago",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "next_billing_date",
                    models.DateField(verbose_name="Próxima Fecha de Pago"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Activa?"),
                ),
                (
                    "auto_pay",
                    models.BooleanField(
                        default=False, verbose_name="¿Pago Automático?"
                    ),
                ),
                (
                    "alert_days_before",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Días de Alerta Anticipada"
                    ),
                ),
                (
                    "last_processed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Fecha Procesada"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="finance.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
                "ordering": ["next_billing_date"],
            },
        ),
    ]
