# Generated by Django 5.2.12 on 2026-03-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("warning", "Advertencia (80%)"),
                            ("critical", "Crítica (100%)"),
                            ("info", "Información"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Límite mensual"
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(verbose_name="Mes (1-12)")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Año")),
                (
                    "alerted_80",
                    models.BooleanField(
                        default=False, verbose_name="Alerta 80% enviada"
                    ),
                ),
                (
                    "alerted_100",
                    models.BooleanField(
                        default=False, verbose_name="Alerta 100% enviada"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="finance.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "unique_together": {("user", "category", "month", "year")},
            },
        ),
    ]
