# Generated by Django 5.2.14 on 2026-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='critical_threshold',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Umbral crítico (%)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='warning_threshold',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Umbral de advertencia (%)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='alerted_100',
            field=models.BooleanField(default=False, verbose_name='Alerta crítica enviada'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='alerted_80',
            field=models.BooleanField(default=False, verbose_name='Alerta advertencia enviada'),
        ),
    ]
